name: Salesforce CI/CD - Production Only

on:
  push:
    branches:
      - main

jobs:
  deploy_prod:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Salesforce CLI using official GitHub Action
      - name: Install Salesforce CLI
        uses: salesforcecli/github-action@v2

      # Step 3: Create JWT key file from GitHub secret
      - name: Create JWT key file
        run: echo "${{ secrets.JWT_KEY }}" > server.key

      # Step 4: Authenticate to Salesforce Production
      - name: Authenticate to Production
        run: sf auth jwt grant \
              --username "${{ secrets.SF_USERNAME_PROD }}" \
              --jwt-key-file server.key \
              --client-id "${{ secrets.SF_CONSUMER_KEY_PROD }}" \
              --instance-url "${{ secrets.SF_LOGIN_URL_PROD }}"

      # Step 5: Deploy Metadata to Production
      - name: Deploy Metadata
        run: sf project deploy start \
              --target-org "${{ secrets.SF_USERNAME_PROD }}" \
              --verbose
