name: Salesforce CI/CD - Production Only - New Changes

on:
  push:
    branches:
      - main

jobs:
  deploy_prod:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Salesforce CLI via npm
      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --location=global
          nodeInstallPath=$(npm config get prefix)
          echo "$nodeInstallPath/bin" >> $GITHUB_PATH

      # Step 3: Create JWT key file from GitHub secret
      - name: Create JWT key file
        run: echo "${{ secrets.JWT_SERVER_KEY }}" > server.key


